INSERT INTO roles (role_name) VALUES
    ('ADMIN'),
    ('RECRUITER'),
    ('USER');

INSERT INTO credentials (email, password, role_id, is_active, created_at, updated_at)
VALUES
(
    'admin@jobportal.com',
    '{noop}password',
    1,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'pavan.kalyan@gmail.com',
    '$2a$10$7EqJtq98hPqEX7fNZaFWoOhi5Qf5cCBw7O3ZXk4Br5qv4QF6n1r9m',
    2,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'rahul.shetty@gmail.com',
    '$2a$10$7EqJtq98hPqEX7fNZaFWoOhi5Qf5cCBw7O3ZXk4Br5qv4QF6n1r9m',
    2,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'sneha.reddy@gmail.com',
    '$2a$10$7EqJtq98hPqEX7fNZaFWoOhi5Qf5cCBw7O3ZXk4Br5qv4QF6n1r9m',
    2,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'arjun.kumar@gmail.com',
    '$2a$10$7EqJtq98hPqEX7fNZaFWoOhi5Qf5cCBw7O3ZXk4Br5qv4QF6n1r9m',
    2,
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);
